trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: PushApp 
    displayName: Push app
    jobs:
    - job: BuildImage
      displayName: Build image
      steps:
      - script: |
          echo ****Display****   
          ls -la
        workingDirectory: '$(Pipeline.Workspace)/s'
        displayName: 'Display  Workspace'

      - task: Docker@2 
        displayName: Build and push images Dev
        inputs:
          containerRegistry: 'Docker-Registry-NttData'
          repository: '$(DOCKER_REPOSITORY)'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'

      - task: PublishPipelineArtifact@1
        displayName: 'Publish deployment.yml as an artifact'
        inputs:
          targetPath: '$(Pipeline.Workspace)/s/manifest/deployment.yml'
          artifact: 'manifest'
          artifactName: 'manifest'
          publishLocation: 'pipeline'
