trigger:
- master

stages:
  - stage: PushApp 
    displayName: Push app
    jobs:
    - job: PreBuild
      displayName: Prepare build
      pool:
        vmImage: 'macOS-latest'
      steps:
      - checkout: self
        clean: true
        persistCredentials: true
        displayName: 'Checkout Git Repo'
      - task: NodeTool@0
        inputs:
          versionSpec: '14.16.1'
        displayName: 'Install Node'
      - script: npm install
        displayName: 'Install packages'
      - script: git fetch --tags
        displayName: 'Fetch tags'
      - script: git tag -l | sort -V | tail -n 1 | xargs npm version --no-git-tag-version --allow-same-version
        displayName: Update package.json locally with latest version number
      - task: Npm@1
        displayName: 'Generate changelog and calculate version number'
        inputs:
          command: 'custom'
          customCommand: 'run changelog'
        # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      - script: git push --follow-tags origin HEAD:$(Build.SourceBranchName)
        displayName: 'Push git tag'
        # condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
      - script: echo "##vso[task.setvariable variable=tag;]$(git describe --tags $(git rev-list --tags --max-count=1))"
        displayName: Set tag variable
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Pipeline Artifact'
        inputs:
          targetPath: '$(Build.SourcesDirectory)'
          artifact: 'msresolver'
          publishLocation: 'pipeline'
    - job: BuildImage
      displayName: Build image
      dependsOn: PreBuild
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - checkout: none
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: 'msresolver'
          targetPath: $(Build.SourcesDirectory)
      - script: |
          echo ****Display****   
          ls -la
        workingDirectory: '$(Pipeline.Workspace)/s'
        displayName: 'Display  Workspace'

      - task: Docker@2 
        displayName: Build and push images Dev
        inputs:
          containerRegistry: 'Docker-Registry-NttData'
          repository: '$(DOCKER_REPOSITORY)'
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(tag)
            latest
            dev
          # ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
          #   tags: |
          #     $(tag)
          # ${{ else }}:
          #   tags: |
          #     dev
